homeassistant:
  name: Home
  customize: !include customize.yaml
  elevation: 94
  unit_system: imperial
  latitude: !secret home_lat
  longitude: !secret home_long
  time_zone: America/Chicago

# Enable configuration panel
config:

lovelace:
  mode: yaml

logger:
  default: info
  logs:
    homeassistant.core: debug

# Enable map panel
map:

recorder:
  purge_interval: 1
  purge_keep_days: 7

ios:

sun:

weather:
  - platform: yweather
    woeid: !secret yahoo_woeid

custom_updater:
  card_urls:
    - https://raw.githubusercontent.com/kalkih/mini-graph-card/master/tracker.json

zone:
  name: Andrew Work
  latitude: !secret andrew_work_lat
  longitude: !secret andrew_work_long
  radius: 500
  icon: mdi:worker

zone 2:
  name: Bethany Work
  latitude: !secret bethany_work_lat
  longitude: !secret bethany_work_long
  radius: 200
  icon: mdi:worker

zone 3:
  name: Dan and Marilyn's
  latitude: !secret dan_lat
  longitude: !secret dan_long
  radius: 500
  icon: mdi:home-variant

zone 4:
  name: Wayne and Lisa's
  latitude: !secret wayne_lat
  longitude: !secret wanye_long
  radius: 500
  icon: mdi:home-variant

zone 5:
  name: Michael and Mandy's
  latitude: !secret michael_lat
  longitude: !secret michael_long
  radius: 500
  icon: mdi:home-variant

zone 6:
  name: Kimberly and Travis'
  latitude: !secret travis_lat
  longitude: !secret travis_long
  radius: 500
  icon: mdi:home-variant

proximity:
  home:
    devices:
      - device_tracker.owntracks_android
      - device_tracker.bethanys_iphone
    tolerance: 50
    unit_of_measurement: mi

apcupsd:
  host: 10.0.1.6
  port: 3551

# Checks for available updates
updater:
  include_used_components: true

# Enables the frontend
frontend:
  javascript_version: latest
  themes:
    darkred:
      # Main colors that can be changed
      dark-primary-color: "#c66900"
      disabled-text-color: "#545454"
      divider-color: "rgba(255, 255, 255, 0.12)"
      light-primary-color: "#e06c6c"
      paper-card-background-color: "#1d1d1d"
      paper-grey-200: "#191919"
      paper-item-icon-color: "#d3d3d3"
      paper-listbox-background-color: "#202020"
      primary-background-color: "#303030"
      primary-color: "#d32f2f"
      primary-text-color: "#cfcfcf"
      secondary-background-color: "#131313"
      sidebar-text_-_background: "#62717b"
      # Colors based on variables, see above
      paper-card-header-color: "var(--paper-item-icon-color)"
      paper-item-icon-active-color: "var(--primary-color)"
      paper-item-icon_-_color: "var(--primary-text-color)"
      paper-listbox-color: "var(--primary-text-color)"
      paper-grey-50: "var(--primary-text-color)"
      paper-slider-active-color: "var(--primary-color)"
      paper-slider-knob-color: "var(--primary-color)"
      paper-slider-knob-start-color: "var(--primary-color)"
      paper-slider-pin-color: "var(--primary-color)"
      paper-slider-secondary-color: "var(--light-primary-color)"
      paper-toggle-button-checked-ink-color: "var(--dark-primary-color)"
      paper-toggle-button-checked-button-color: "var(--primary-color)"
      paper-toggle-button-checked-bar-color: "var(--light-primary-color)"
      paper-toggle-button-unchecked-bar-color: "var(--primary-text-color)"
      secondary-text-color: "var(--primary-color)"
      table-row-background-color: "var(--paper-card-background-color)"
      table-row-alternative-background-color: "var(--sidebar-text_-_background)"

    midnight-remake:
      # Main colors
      primary-color: '#2980b9'
      accent-color: '#f1c40f'
      dark-primary-color: 'var(--accent-color)'
      light-primary-color: 'var(--accent-color)'

      # Text colors
      primary-text-color: '#ffffff'
      text-primary-color: 'var(--primary-text-color)'
      secondary-text-color: 'var(--accent-color)'
      disabled-text-color: '#e5e5e5'
      label-badge-border-color: 'green'

      # Sidebar
      sidebar-icon-color: 'var(--primary-text-color)'
      sidebar-selected-icon-color: 'var(--accent-color)'
      sidebar-selected-background-color: 'rgba(255, 255, 255, .1)'

      # Background colors
      primary-background-color: '#2c3e50'
      secondary-background-color: '#2c3e50'
      divider-color: 'rgba(0, 0, 0, .12)'

      # Table rows
      table-row-background-color: '#2c3e50'
      table-row-alternative-background-color: '#2B3E50'

      # Nav Menu
      paper-listbox-color: 'var(--primary-text-color)'
      paper-listbox-background-color: '#1f2b38'
      paper-grey-50: 'var(--primary-text-color)'
      paper-grey-200: '#2B3E50'

      # Paper card
      paper-card-header-color: 'var(--accent-color)'
      paper-card-background-color: '#34495e'
      paper-dialog-background-color: '#34495e'
      paper-item-icon-color: 'var(--primary-text-color)'
      paper-item-icon-active-color: '#F9C536'
      paper-item-icon_-_color: 'var(--primary-text-color)'
      paper-item-selected_-_background-color: '#34495e'
      paper-tabs-selection-bar-color: 'var(--primary-text-color)'

      # Labels
      label-badge-red: 'var(--accent-color'
      label-badge-text-color: 'var(--primary-text-color'
      label-badge-background-color: '#2E333A'

      # Switches
      paper-toggle-button-checked-button-color: 'var(--accent-color)'
      paper-toggle-button-checked-bar-color: 'var(--accent-color)'
      paper-toggle-button-checked-ink-color: 'var(--accent-color)'
      paper-toggle-button-unchecked-button-color: 'var(--disabled-text-color)'
      paper-toggle-button-unchecked-bar-color: 'var(--disabled-text-color)'
      paper-toggle-button-unchecked-ink-color: 'var(--disabled-text-color)'

      # Sliders
      paper-slider-knob-color: '#F9C536'
      paper-slider-knob-start-color: 'var(--accent-color)'
      paper-slider-pin-color: '#F9C536'
      paper-slider-active-color: 'var(--accent-color)'
      paper-slider-container-color: 'linear-gradient(var(--primary-background-color), var(--secondary-background-color)) no-repeat'
      paper-slider-secondary-color: 'var(--secondary-background-color)'
      paper-slider-disabled-active-color: 'var(--disabled-text-color)'
      paper-slider-disabled-secondary-color: 'var(--disabled-text-color)'

      # Google colors
      google-red-500: 'var(--accent-color)'
      google-green-500: '#27ae60'

# Enables support for tracking state changes over time.
history:
  exclude:
    entities:
      - sensor.last_boot
      - sensor.moon_phase
      - sensor.bed_toggle_switch
      - sensor.ac_history
      - sensor.dark_sky_icon
      - sensor.dark_sky_summary
    domains:
      - automation
      - camera
      - group
      - notify
      - scene
      - script
      - shell_command
      - sun
      - zone
      - zwave

# View all events in a logbook
logbook:
  exclude:
    entities:
      - sensor.average_load_1m

http:
  api_password: !secret api_password
  use_x_forwarded_for: true
  trusted_proxies: 
    - 127.0.0.1
    - ::1
  server_port: 8123

#Local MQTT Only (local devices publish here, and I subscribe over ssl via bridged remote MQTT)
mqtt:
  broker: 127.0.0.1
  port: 1883
  keepalive: 60
  username: !secret owntracks_user
  password: !secret owntracks_password

influxdb:
  host: localhost
  username: !secret influx_user
  password: !secret influx_password

ifttt:
  key: !secret ifttt_key

zwave:
  usb_path: /dev/zwave

wemo:
  static:
    - 10.0.1.48

emulated_hue:
  expose_by_default: false
  #See customize.yaml for exposed entites

#Seems to be broken, makes HASS hang..
arlo:
  username: !secret arlo_username
  password: !secret arlo_password

panel_iframe:
  plane_tracking:
    title: 'Plane Tracking'
    icon: mdi:airplane
    url: !secret plane
  ups:
    title: 'UPS Status'
    icon: mdi:car-battery
    url: !secret ups
  grafana:
    title: 'Grafana'
    icon: mdi:chart-areaspline
    url: !secret grafana

alexa:

google_assistant:
  project_id: home-assistant-158717
  api_key: !secret homegraph

#usps:
#  driver: chrome
#  username: !secret usps_username
#  password: !secret usps_key

owntracks:

device_tracker:
  - platform: nmap_tracker
    hosts: 10.0.1.13/32
    home_interval: 10
  - platform: tile
    username: !secret tile_user
    password: !secret tile_password

media_player:
  - platform: spotify
    client_id: !secret spotify_client_id
    client_secret: !secret spotify_client_secret
  - platform: plex
  - platform: alexa
    email: !secret amazon_email
    password: !secret amazon_pass
    url: "amazon.com"

climate:
  platform: radiotherm
  host:
    - 10.0.1.29
  hold_temp: True

notify:
  - platform: pushbullet
    api_key: !secret pushbullet_key
    name: pushbullet
  - platform: pushover
    name: pushover
    api_key: !secret pushover_api_key
    user_key: !secret pushover_user_key

light:
  - platform: limitlessled
    bridges:
      - host: 10.0.1.47
        version: 5
        port: 8899
        groups:
        - number: 1
          type: rgbw
          name: master_bedroom
          fade: on
        - number: 2
          type: rgbw
          name: andrew_monitor_backlight
          fade: on

netatmo:
  api_key: !secret netatmo_key
  secret_key: !secret netatmo_secret
  username: !secret netatmo_user
  password: !secret netatmo_pass

digital_ocean:
  access_token: !secret DO_token

intent_script: !include intent_script.yaml
camera: !include camera.yaml
switch: !include switches.yaml
binary_sensor: !include binary_sensor.yaml
sensor: !include sensors.yaml
automation: !include automation.yaml
group: !include group.yaml
scene: !include scene.yaml
script: !include scripts.yaml
input_boolean: !include input_boolean.yaml
input_select: !include input_select.yaml
shell_command: !include shell_command.yaml
rest_command: !include rest_command.yaml
